---
include:
- /.gitlab-ci/variables.yml
- /.gitlab-ci/extends.yml
#
- '/k8s/elasticsearch/.deploy-elasticsearch-k8s.yml'
- '/k8s/code-du-travail-data/.deploy-code-du-travail-data-k8s.yml'
- '/k8s/code-du-travail-api/.deploy-code-du-travail-api-k8s.yml'
- '/k8s/code-du-travail-frontend/.deploy-code-du-travail-frontend-k8s.yml'
- '/k8s/code-du-travail-nlp/.deploy-code-du-travail-nlp-k8s.yml'
#
- /.gitlab-ci/stages/prepare.yml
- /.gitlab-ci/stages/quality.yml
- /.gitlab-ci/stages/register.yml
- /.gitlab-ci/stages/notify.yml

image: node:10-alpine

stages:
- "Prepare"
- "Code Quality"
- "Registration"
- "Deploy EL Stack"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Deploy Code du Travail Numerique"
- "Notify Finished Deployment"
- "Delete Pods"

######################################
### DEPLOY CDTN TO K8S DEV CLUSTER ###
######################################

deploy-elasticsearch:
  stage: "Deploy EL Stack"
  extends: .deploy-elasticsearch-dev-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA
    ES_PORT: ${ELASTICSEARCH_PORT}
    ES_INTER_NODE: ${ELASTICSEARCH_INTER_NODE_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  except:
  - master

create-cdtn-es-index:
  stage: "Create Code du Travail Numerique Elasticsearch Index"
  extends: .deploy-code-du-travail-data-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA
    ES_PORT: ${ELASTICSEARCH_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  except:
  - master

deploy-cdtn-api:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-api-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA
    ELASTICSEARCH_LOG_LEVEL: "trace"
    APM_SERVER_ACTIVE: 0
    APM_SERVER_URL: ""
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    PORT: ${API_PORT}
    ES_PORT: ${ELASTICSEARCH_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: dev
  except:
  - master

deploy-cdtn-nlp:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-nlp-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    FLASK_APP: ${FLASK_APP}
    PORT: ${NLP_PORT}
    SUGGEST_DATA: ${SUGGEST_DATA_URL}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: dev
  except:
  - master

deploy-cdtn-frontend:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-frontend-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    PORT: ${FRONTEND_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: dev
  except:
  - master

########################################
#### DEPLOY CDTN TO K8S PROD CLUSTER ###
########################################

deploy-elasticsearch-prod:
  stage: "Deploy EL Stack"
  extends: .deploy-elasticsearch-prod-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
    IMAGE_TAG: $CI_COMMIT_SHA
    HASH_BRANCH_NAME: ''
    ES_PORT: ${ELASTICSEARCH_PORT}
    ES_INTER_NODE: ${ELASTICSEARCH_INTER_NODE_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  only:
  - master

create-cdtn-es-index-prod:
  stage: "Create Code du Travail Numerique Elasticsearch Index"
  extends: .deploy-code-du-travail-data-prod-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
    IMAGE_TAG: $CI_COMMIT_SHA
    HASH_BRANCH_NAME: ''
    ES_PORT: ${ELASTICSEARCH_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  only:
  - master

deploy-cdtn-api-prod:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-api-prod-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
    IMAGE_TAG: $CI_COMMIT_SHA
    HASH_BRANCH_NAME: ''
    ELASTICSEARCH_LOG_LEVEL: "trace"
    APM_SERVER_ACTIVE: 0
    APM_SERVER_URL: ""
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    PORT: ${API_PORT}
    ES_PORT: ${ELASTICSEARCH_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: ops
  only:
  - master

deploy-cdtn-nlp-prod:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-nlp-prod-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
    IMAGE_TAG: $CI_COMMIT_SHA
    HASH_BRANCH_NAME: ''
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    FLASK_APP: ${FLASK_APP}
    PORT: ${NLP_PORT}
    SUGGEST_DATA: ${SUGGEST_DATA_URL}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: ops
  only:
  - master

deploy-cdtn-frontend-prod:
  stage: "Deploy Code du Travail Numerique"
  extends: .deploy-code-du-travail-frontend-prod-k8s
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
    IMAGE_TAG: $CI_COMMIT_SHA
    HASH_BRANCH_NAME: ''
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    PORT: ${FRONTEND_PORT}
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
  environment:
    name: ops
  only:
  - master

#######################################
###           DELETE PODS           ###
#######################################

delete-pods:
  stage: "Delete Pods"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  variables:
    K8S_SERVER: $K8S_SERVER_PROD
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_PROD
    K8S_NAMESPACE: $K8S_NAMESPACE_PROD
    K8S_USERNAME: $K8S_USERNAME_PROD
    K8S_CONTEXT: $K8S_CONTEXT_PROD
    K8S_TOKEN: $K8S_TOKEN_PROD
  before_script:
  - /apps/create-kubeconfig.sh
  script:
  - python3 k8s/scripts/delete-pods.py
  only:
  - master
