version: '3'

services:

  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: $NODE_ENV
        API_URL: $API_URL
        SENTRY_PUBLIC_DSN: $SENTRY_PUBLIC_DSN
        PIWIK_URL: $PIWIK_URL
        PIWIK_SITE_ID: $PIWIK_SITE_ID
    ports:
      - $PORT:$PORT
    restart: always
